
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int SHR_ASSIGN = 41;
  public static final int XOR_ASSIGN = 42;
  public static final int DEC_OP = 33;
  public static final int CHAR = 50;
  public static final int XOR = 13;
  public static final int INTEGER = 46;
  public static final int SHR_OP = 31;
  public static final int CONTINUE = 58;
  public static final int GREATER = 16;
  public static final int INT = 51;
  public static final int PARAR = 3;
  public static final int INC_OP = 32;
  public static final int FOR = 57;
  public static final int LESS = 15;
  public static final int CURLYR = 8;
  public static final int TILDE = 21;
  public static final int GE_OP = 29;
  public static final int CHARACTER = 47;
  public static final int PARAL = 2;
  public static final int SIZEOF = 61;
  public static final int SUB_ASSIGN = 39;
  public static final int NOT = 22;
  public static final int CURLYL = 7;
  public static final int PTR_OP = 34;
  public static final int OR = 12;
  public static final int NE_OP = 27;
  public static final int COMMA = 5;
  public static final int DIV = 19;
  public static final int SQUARR = 10;
  public static final int OR_OP = 24;
  public static final int IF = 54;
  public static final int ASSIGN = 6;
  public static final int DOT = 23;
  public static final int AND_OP = 25;
  public static final int SQUARL = 9;
  public static final int ADD_ASSIGN = 38;
  public static final int EOF = 0;
  public static final int RETURN = 60;
  public static final int error = 1;
  public static final int SHL_ASSIGN = 40;
  public static final int MUL = 11;
  public static final int ADD = 17;
  public static final int MOD = 20;
  public static final int BREAK = 59;
  public static final int VOID = 49;
  public static final int ADRESS = 14;
  public static final int MOD_ASSIGN = 37;
  public static final int DIV_ASSIGN = 36;
  public static final int COLON = 4;
  public static final int UNION = 53;
  public static final int ELSE = 55;
  public static final int SHL_OP = 30;
  public static final int AND_ASSIGN = 44;
  public static final int EQ_OP = 26;
  public static final int WHILE = 56;
  public static final int OR_ASSIGN = 43;
  public static final int MUL_ASSIGN = 35;
  public static final int STRING = 48;
  public static final int LE_OP = 28;
  public static final int STRUCT = 52;
  public static final int SUB = 18;
  public static final int IDENTIFIER = 45;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PARAL",
  "PARAR",
  "COLON",
  "COMMA",
  "ASSIGN",
  "CURLYL",
  "CURLYR",
  "SQUARL",
  "SQUARR",
  "MUL",
  "OR",
  "XOR",
  "ADRESS",
  "LESS",
  "GREATER",
  "ADD",
  "SUB",
  "DIV",
  "MOD",
  "TILDE",
  "NOT",
  "DOT",
  "OR_OP",
  "AND_OP",
  "EQ_OP",
  "NE_OP",
  "LE_OP",
  "GE_OP",
  "SHL_OP",
  "SHR_OP",
  "INC_OP",
  "DEC_OP",
  "PTR_OP",
  "MUL_ASSIGN",
  "DIV_ASSIGN",
  "MOD_ASSIGN",
  "ADD_ASSIGN",
  "SUB_ASSIGN",
  "SHL_ASSIGN",
  "SHR_ASSIGN",
  "XOR_ASSIGN",
  "OR_ASSIGN",
  "AND_ASSIGN",
  "IDENTIFIER",
  "INTEGER",
  "CHARACTER",
  "STRING",
  "VOID",
  "CHAR",
  "INT",
  "STRUCT",
  "UNION",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "CONTINUE",
  "BREAK",
  "RETURN",
  "SIZEOF"
  };
}

