/* The following code was generated by JFlex 1.6.1 */

/*
lexer specification for loliccompiler for Jflex by RobbinNi
*/

package lexer


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>D:/4415 ±‡“Î‘≠¿Ì MS109/loliccompiler/src/lexer/loliccompiler.flex</tt>
 */
class lexer implements java_cup.runtime.Scanner, Symbols {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\16\1\70\1\46"+
    "\1\15\1\7\1\66\1\17\1\21\1\47\1\50\1\5\1\64\1\52"+
    "\1\65\1\71\1\4\1\11\3\24\4\12\2\10\1\15\1\51\1\62"+
    "\1\53\1\63\2\15\6\14\24\6\1\56\1\20\1\57\1\61\2\7"+
    "\1\33\1\23\1\31\1\30\1\41\1\40\1\6\1\32\1\27\1\6"+
    "\1\44\1\42\1\6\1\35\1\26\2\6\1\34\1\36\1\22\1\37"+
    "\1\25\1\43\1\13\1\6\1\45\1\54\1\60\1\55\1\67\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uff91\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\1\4\1\5\1\1\2\6"+
    "\1\2\1\7\1\1\12\5\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\2\0\1\40\1\41\1\5"+
    "\2\6\1\0\1\42\1\43\1\44\1\0\1\44\1\0"+
    "\3\5\1\45\11\5\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\1\54\1\55\1\56\1\57\1\60\1\61\1\62"+
    "\1\63\1\64\1\65\1\0\1\66\1\67\1\70\1\0"+
    "\1\71\1\72\1\73\1\74\2\37\3\0\1\6\2\0"+
    "\2\5\1\75\6\5\1\76\2\5\1\77\1\100\3\0"+
    "\1\5\1\101\1\5\1\102\4\5\1\103\1\5\1\104"+
    "\1\105\4\5\1\106\1\107\1\5\1\110\1\111\1\112"+
    "\1\5\1\113";

  private static int [] zzUnpackAction() {
    int [] result = new int[149];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\72\0\164\0\256\0\164\0\350\0\u0122\0\u015c"+
    "\0\u0196\0\u01d0\0\u020a\0\u0196\0\u0244\0\u027e\0\u02b8\0\u02f2"+
    "\0\u032c\0\u0366\0\u03a0\0\u03da\0\u0414\0\u044e\0\u0488\0\u04c2"+
    "\0\u0196\0\u0196\0\u0196\0\u0196\0\u0196\0\u04fc\0\u0196\0\u0196"+
    "\0\u0196\0\u0196\0\u0536\0\u0570\0\u05aa\0\u05e4\0\u061e\0\u0658"+
    "\0\u0692\0\u0196\0\u06cc\0\u0196\0\u0706\0\u0740\0\164\0\u077a"+
    "\0\u07b4\0\u07ee\0\164\0\164\0\u0828\0\u0862\0\u089c\0\u08d6"+
    "\0\u07ee\0\164\0\u0910\0\u094a\0\164\0\u0910\0\u0984\0\u09be"+
    "\0\u09f8\0\u0828\0\u0a32\0\u0a6c\0\u0aa6\0\u0ae0\0\u0b1a\0\u0b54"+
    "\0\u0b8e\0\u0bc8\0\u0c02\0\164\0\164\0\164\0\164\0\164"+
    "\0\u0c3c\0\164\0\u0c76\0\164\0\164\0\164\0\164\0\164"+
    "\0\164\0\164\0\u0cb0\0\u0cea\0\164\0\164\0\164\0\u0cb0"+
    "\0\164\0\164\0\164\0\164\0\u0d24\0\164\0\u0d5e\0\u0d98"+
    "\0\u0dd2\0\u08d6\0\u0e0c\0\u0e46\0\u0e80\0\u0eba\0\u0828\0\u0ef4"+
    "\0\u0f2e\0\u0f68\0\u0fa2\0\u0fdc\0\u1016\0\u0828\0\u1050\0\u108a"+
    "\0\164\0\164\0\u10c4\0\u10fe\0\u1138\0\u1172\0\u0828\0\u11ac"+
    "\0\u0828\0\u11e6\0\u1220\0\u125a\0\u1294\0\u0828\0\u12ce\0\164"+
    "\0\u0828\0\u1308\0\u1342\0\u137c\0\u13b6\0\u0828\0\u0828\0\u13f0"+
    "\0\u0828\0\u0828\0\u0828\0\u142a\0\u0828";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[149];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\2\5\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\12\2\10\1\11\1\14\1\15\1\16\1\11"+
    "\1\10\1\17\1\12\1\20\1\10\1\21\1\10\1\22"+
    "\2\10\1\23\1\10\1\24\1\25\1\26\1\27\1\10"+
    "\1\30\2\10\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\1\54\1\55\2\3"+
    "\15\55\1\56\25\55\1\57\23\55\74\0\1\5\73\0"+
    "\1\60\1\61\11\0\1\62\33\0\1\63\35\0\1\62"+
    "\33\0\1\64\24\0\7\65\2\0\1\62\1\65\1\0"+
    "\24\65\10\0\2\65\1\0\1\65\27\0\1\62\62\0"+
    "\3\66\4\0\1\62\4\0\1\66\56\0\2\67\1\70"+
    "\3\0\1\62\4\0\1\67\64\0\1\71\33\0\1\72"+
    "\27\0\1\73\1\0\1\74\3\0\1\62\4\75\1\76"+
    "\7\0\2\75\2\0\1\75\5\0\1\75\31\0\7\65"+
    "\2\0\1\62\1\65\1\0\12\65\1\77\11\65\10\0"+
    "\2\65\1\0\1\65\16\0\7\65\2\0\1\62\1\65"+
    "\1\0\4\65\1\100\17\65\10\0\2\65\1\0\1\65"+
    "\16\0\7\65\2\0\1\62\1\65\1\0\13\65\1\101"+
    "\2\65\1\102\5\65\10\0\2\65\1\0\1\65\16\0"+
    "\7\65\2\0\1\62\1\65\1\0\4\65\1\103\3\65"+
    "\1\104\13\65\10\0\2\65\1\0\1\65\16\0\7\65"+
    "\2\0\1\62\1\65\1\0\17\65\1\105\4\65\10\0"+
    "\2\65\1\0\1\65\16\0\7\65\2\0\1\62\1\65"+
    "\1\0\1\106\4\65\1\107\16\65\10\0\2\65\1\0"+
    "\1\65\16\0\7\65\2\0\1\62\1\65\1\0\13\65"+
    "\1\110\10\65\10\0\2\65\1\0\1\65\16\0\7\65"+
    "\2\0\1\62\1\65\1\0\4\65\1\111\17\65\10\0"+
    "\2\65\1\0\1\65\16\0\7\65\2\0\1\62\1\65"+
    "\1\0\20\65\1\112\3\65\10\0\2\65\1\0\1\65"+
    "\16\0\7\65\2\0\1\62\1\65\1\0\10\65\1\113"+
    "\13\65\10\0\2\65\1\0\1\65\27\0\1\62\33\0"+
    "\1\114\35\0\1\62\33\0\1\115\4\0\1\116\30\0"+
    "\1\62\33\0\1\117\35\0\1\62\33\0\1\120\6\0"+
    "\1\121\26\0\1\62\33\0\1\122\7\0\1\123\25\0"+
    "\1\62\33\0\1\124\10\0\1\125\24\0\1\62\33\0"+
    "\1\126\7\0\1\127\1\0\1\130\23\0\1\62\33\0"+
    "\1\131\35\0\1\62\33\0\1\132\16\0\1\55\2\0"+
    "\15\55\1\0\25\55\1\0\23\55\11\0\1\133\1\0"+
    "\1\134\5\0\1\135\1\136\1\137\1\140\7\0\1\141"+
    "\1\142\2\0\1\143\5\0\1\144\23\0\1\60\1\145"+
    "\1\146\67\60\5\147\1\150\64\147\17\0\1\151\60\0"+
    "\7\65\3\0\1\65\1\0\24\65\10\0\2\65\1\0"+
    "\1\65\20\0\3\66\11\0\1\66\56\0\2\67\11\0"+
    "\1\67\55\0\3\152\1\0\1\152\6\0\2\152\3\0"+
    "\2\152\1\0\1\152\4\0\2\152\41\0\2\153\11\0"+
    "\1\153\55\0\3\154\1\0\1\154\6\0\2\154\3\0"+
    "\2\154\1\0\1\154\4\0\2\154\36\0\7\65\3\0"+
    "\1\65\1\0\17\65\1\155\4\65\10\0\2\65\1\0"+
    "\1\65\16\0\7\65\3\0\1\65\1\0\5\65\1\156"+
    "\16\65\10\0\2\65\1\0\1\65\16\0\7\65\3\0"+
    "\1\65\1\0\1\157\23\65\10\0\2\65\1\0\1\65"+
    "\16\0\7\65\3\0\1\65\1\0\13\65\1\160\10\65"+
    "\10\0\2\65\1\0\1\65\16\0\7\65\3\0\1\65"+
    "\1\0\11\65\1\161\12\65\10\0\2\65\1\0\1\65"+
    "\16\0\7\65\3\0\1\65\1\0\1\162\23\65\10\0"+
    "\2\65\1\0\1\65\16\0\7\65\3\0\1\65\1\0"+
    "\12\65\1\163\11\65\10\0\2\65\1\0\1\65\16\0"+
    "\7\65\3\0\1\65\1\0\23\65\1\164\10\0\2\65"+
    "\1\0\1\65\16\0\7\65\3\0\1\65\1\0\5\65"+
    "\1\165\16\65\10\0\2\65\1\0\1\65\16\0\7\65"+
    "\3\0\1\65\1\0\12\65\1\166\11\65\10\0\2\65"+
    "\1\0\1\65\16\0\7\65\3\0\1\65\1\0\14\65"+
    "\1\167\7\65\10\0\2\65\1\0\1\65\16\0\7\65"+
    "\3\0\1\65\1\0\5\65\1\170\16\65\10\0\2\65"+
    "\1\0\1\65\63\0\1\171\71\0\1\172\27\0\2\173"+
    "\11\0\1\173\55\0\3\174\1\0\1\174\6\0\2\174"+
    "\3\0\2\174\1\0\1\174\4\0\2\174\32\0\1\146"+
    "\67\0\5\147\1\175\64\147\4\0\1\146\1\150\64\0"+
    "\20\75\2\0\24\75\1\0\23\75\11\0\2\75\11\0"+
    "\1\75\55\0\3\75\1\0\1\75\6\0\2\75\3\0"+
    "\2\75\1\0\1\75\4\0\2\75\36\0\7\65\3\0"+
    "\1\65\1\0\11\65\1\176\12\65\10\0\2\65\1\0"+
    "\1\65\16\0\7\65\3\0\1\65\1\0\6\65\1\177"+
    "\15\65\10\0\2\65\1\0\1\65\16\0\7\65\3\0"+
    "\1\65\1\0\1\200\23\65\10\0\2\65\1\0\1\65"+
    "\16\0\7\65\3\0\1\65\1\0\12\65\1\201\11\65"+
    "\10\0\2\65\1\0\1\65\16\0\7\65\3\0\1\65"+
    "\1\0\15\65\1\202\6\65\10\0\2\65\1\0\1\65"+
    "\16\0\7\65\3\0\1\65\1\0\15\65\1\203\6\65"+
    "\10\0\2\65\1\0\1\65\16\0\7\65\3\0\1\65"+
    "\1\0\17\65\1\204\4\65\10\0\2\65\1\0\1\65"+
    "\16\0\7\65\3\0\1\65\1\0\4\65\1\205\17\65"+
    "\10\0\2\65\1\0\1\65\16\0\7\65\3\0\1\65"+
    "\1\0\17\65\1\206\4\65\10\0\2\65\1\0\1\65"+
    "\16\0\7\65\3\0\1\65\1\0\20\65\1\207\3\65"+
    "\10\0\2\65\1\0\1\65\21\0\2\210\11\0\1\210"+
    "\55\0\3\210\1\0\1\210\6\0\2\210\3\0\2\210"+
    "\1\0\1\210\4\0\2\210\30\0\4\147\1\146\1\175"+
    "\64\147\6\0\7\65\3\0\1\65\1\0\22\65\1\211"+
    "\1\65\10\0\2\65\1\0\1\65\16\0\7\65\3\0"+
    "\1\65\1\0\5\65\1\212\16\65\10\0\2\65\1\0"+
    "\1\65\16\0\7\65\3\0\1\65\1\0\12\65\1\213"+
    "\11\65\10\0\2\65\1\0\1\65\16\0\7\65\3\0"+
    "\1\65\1\0\7\65\1\214\14\65\10\0\2\65\1\0"+
    "\1\65\16\0\7\65\3\0\1\65\1\0\4\65\1\215"+
    "\17\65\10\0\2\65\1\0\1\65\16\0\7\65\3\0"+
    "\1\65\1\0\13\65\1\216\10\65\10\0\2\65\1\0"+
    "\1\65\16\0\7\65\3\0\1\65\1\0\17\65\1\217"+
    "\4\65\10\0\2\65\1\0\1\65\16\0\7\65\3\0"+
    "\1\65\1\0\13\65\1\220\10\65\10\0\2\65\1\0"+
    "\1\65\16\0\7\65\3\0\1\65\1\0\13\65\1\221"+
    "\10\65\10\0\2\65\1\0\1\65\16\0\7\65\3\0"+
    "\1\65\1\0\1\222\23\65\10\0\2\65\1\0\1\65"+
    "\16\0\7\65\3\0\1\65\1\0\16\65\1\223\5\65"+
    "\10\0\2\65\1\0\1\65\16\0\7\65\3\0\1\65"+
    "\1\0\15\65\1\224\6\65\10\0\2\65\1\0\1\65"+
    "\16\0\7\65\3\0\1\65\1\0\17\65\1\225\4\65"+
    "\10\0\2\65\1\0\1\65\10\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5220];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\51\1\1\11\1\1\2\0"+
    "\2\11\3\1\1\0\1\1\1\11\1\1\1\0\1\11"+
    "\1\0\15\1\5\11\1\1\1\11\1\1\7\11\1\1"+
    "\1\0\3\11\1\0\4\11\1\1\1\11\3\0\1\1"+
    "\2\0\14\1\2\11\3\0\12\1\1\11\15\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[149];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    String Buffer buffer = new StringBuffer();

    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }

    private Symbol symbol(int type, Object value) {


    private int chNum(char ch) {
        if (ch >= '0' && ch <= '9') {
            return ch - '0';
        } else if (ch >= 'A' && ch <= 'F') {
            return ch - 'A' + 10;
        } else {
            return ch - 'a' + 10;
        }
    }

        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 172) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new Error("Illegal character <" + yytext() + ">\n" + "Found at Line : " + yyline + " Column : " + yycolumn + ".\n");
            }
          case 76: break;
          case 2: 
            { /* ignored */
            }
          case 77: break;
          case 3: 
            { return symbol(sym.DIVIDE);
            }
          case 78: break;
          case 4: 
            { return symbol(sym.MULTIPLY_ASTERISK);
            }
          case 79: break;
          case 5: 
            { return symbol(sym.IDENTIFIER, yytext());
            }
          case 80: break;
          case 6: 
            { return symbol(sym.INTEGER, yytext());
            }
          case 81: break;
          case 7: 
            { return symbol(sym.ADDRESS_BITWISEAND);
            }
          case 82: break;
          case 8: 
            { buffer.setLength(0); yybegin(STRING);
            }
          case 83: break;
          case 9: 
            { return symbol(sym.LEFTRBRACKET);
            }
          case 84: break;
          case 10: 
            { return symbol(sym.RIGHTRBRACKET);
            }
          case 85: break;
          case 11: 
            { return symbol(sym.SEMICOLON);
            }
          case 86: break;
          case 12: 
            { return symbol(sym.COMMA);
            }
          case 87: break;
          case 13: 
            { return symbol(sym.ASSIGN);
            }
          case 88: break;
          case 14: 
            { return symbol(sym.LEFTCBRACKET);
            }
          case 89: break;
          case 15: 
            { return symbol(sym.RIGHTCBRACKET);
            }
          case 90: break;
          case 16: 
            { return symbol(sym.LEFTSBRACKET);
            }
          case 91: break;
          case 17: 
            { return symbol(sym.RIGHTSBRACKET);
            }
          case 92: break;
          case 18: 
            { return symbol(sym.BITWISEOR);
            }
          case 93: break;
          case 19: 
            { return symbol(sym.BITWISEXOR);
            }
          case 94: break;
          case 20: 
            { return symbol(sym.SMALLER);
            }
          case 95: break;
          case 21: 
            { return symbol(sym.GREATER);
            }
          case 96: break;
          case 22: 
            { return symbol(sym.ADD);
            }
          case 97: break;
          case 23: 
            { return symbol(sym.SUBTRACT);
            }
          case 98: break;
          case 24: 
            { return symbol(sym.MOD);
            }
          case 99: break;
          case 25: 
            { return symbol(sym.BITWISENOT);
            }
          case 100: break;
          case 26: 
            { return symbol(sym.NOT);
            }
          case 101: break;
          case 27: 
            { return symbol(sym.DOT);
            }
          case 102: break;
          case 28: 
            { buffer.append(yytext());
            }
          case 103: break;
          case 29: 
            { buffer.append('\\');
            }
          case 104: break;
          case 30: 
            { yybegin(YYINITIAL);
                      return symbol(sym.STRING, buffer.toString());
            }
          case 105: break;
          case 31: 
            { /* ignore */
            }
          case 106: break;
          case 32: 
            { return symbol(sym.DIVASSIGN);
            }
          case 107: break;
          case 33: 
            { return symbol(sym.MULASSIGN);
            }
          case 108: break;
          case 34: 
            { return symbol(sym.AND);
            }
          case 109: break;
          case 35: 
            { return symbol(sym.ANDASSIGN);
            }
          case 110: break;
          case 36: 
            { return symbol(sym.CHAR, yytext().subString(1 , yytext().size() - 2));
            }
          case 111: break;
          case 37: 
            { return symbol(sym.IF);
            }
          case 112: break;
          case 38: 
            { return symbol(sym.EQUAL);
            }
          case 113: break;
          case 39: 
            { return symbol(sym.ORASSIGN);
            }
          case 114: break;
          case 40: 
            { return symbol(sym.OR);
            }
          case 115: break;
          case 41: 
            { return symbol(sym.XORASSIGN);
            }
          case 116: break;
          case 42: 
            { return symbol(sym.SMALLEREQUAL);
            }
          case 117: break;
          case 43: 
            { return symbol(sym.SHIFTLEFT);
            }
          case 118: break;
          case 44: 
            { return symbol(sym.GREATEREQUAL);
            }
          case 119: break;
          case 45: 
            { return symbol(sym.SHIFTRIGHT);
            }
          case 120: break;
          case 46: 
            { return symbol(sym.ADDASSIGN);
            }
          case 121: break;
          case 47: 
            { return symbol(sym.INCREASE);
            }
          case 122: break;
          case 48: 
            { return symbol(sym.SUBASSIGN);
            }
          case 123: break;
          case 49: 
            { return symbol(sym.POINTER);
            }
          case 124: break;
          case 50: 
            { return symbol(sym.DECREASE);
            }
          case 125: break;
          case 51: 
            { return symbol(sym.MODASSIGN);
            }
          case 126: break;
          case 52: 
            { return symbol(sym.NOTEQUAL);
            }
          case 127: break;
          case 53: 
            { buffer.append('\0');
            }
          case 128: break;
          case 54: 
            { buffer.append('\'');
            }
          case 129: break;
          case 55: 
            { buffer.append('\t');
            }
          case 130: break;
          case 56: 
            { buffer.append('\b');
            }
          case 131: break;
          case 57: 
            { buffer.append('\r');
            }
          case 132: break;
          case 58: 
            { buffer.append('\n');
            }
          case 133: break;
          case 59: 
            { buffer.append('\f');
            }
          case 134: break;
          case 60: 
            { buffer.append('\"');
            }
          case 135: break;
          case 61: 
            { return symbol(sym.INT);
            }
          case 136: break;
          case 62: 
            { return symbol(sym.FOR);
            }
          case 137: break;
          case 63: 
            { return symbol(sym.SHLASSIGN);
            }
          case 138: break;
          case 64: 
            { return symbol(sym.SHRASSIGN);
            }
          case 139: break;
          case 65: 
            { return symbol(sym.VOID);
            }
          case 140: break;
          case 66: 
            { return symbol(sym.CHAR);
            }
          case 141: break;
          case 67: 
            { return symbol(sym.ELSE);
            }
          case 142: break;
          case 68: 
            { String t = yytext();
                             char ch;
                             if (t[0] == 'x') {
                                ch = (chNum(t[1]) << 4) | chNum(t[2]);
                             } else {
                                ch = (chNum(t[0]) << 6) | (chNum(t[1]) << 3) | chNum(t[2]);
                             }
                             buffer.append(ch);
            }
          case 143: break;
          case 69: 
            { return symbol(sym.BREAK);
            }
          case 144: break;
          case 70: 
            { return symbol(sym.UNION);
            }
          case 145: break;
          case 71: 
            { return symbol(sym.WHILE);
            }
          case 146: break;
          case 72: 
            { return symbol(sym.RETURN);
            }
          case 147: break;
          case 73: 
            { return symbol(sym.STRUCT);
            }
          case 148: break;
          case 74: 
            { return symbol(sym.SIZEOF);
            }
          case 149: break;
          case 75: 
            { return symbol(sym.CONTINUE);
            }
          case 150: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Converts an int token code into the name of the
   * token by reflection on the cup symbol class/interface sym
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   */
  private String getTokenName(int token) {
    try {
      java.lang.reflect.Field [] classFields = sym.class.getFields();
      for (int i = 0; i < classFields.length; i++) {
        if (classFields[i].getInt(null) == token) {
          return classFields[i].getName();
        }
      }
    } catch (Exception e) {
      e.printStackTrace(System.err);
    }

    return "UNKNOWN TOKEN";
  }

  /**
   * Same as next_token but also prints the token to standard out
   * for debugging.
   *
   * This code was contributed by Karl Meissner <meissnersd@yahoo.com>
   */
  public java_cup.runtime.Symbol debug_next_token() throws java.io.IOException {
    java_cup.runtime.Symbol s = next_token();
    System.out.println( "line:" + (yyline+1) + " col:" + (yycolumn+1) + " --"+ yytext() + "--" + getTokenName(s.sym) + "--");
    return s;
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java lexer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        lexer scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new lexer(reader);
          while ( !scanner.zzAtEOF ) scanner.debug_next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
