/* The following code was generated by JFlex 1.6.1 */

/*
lexer specification for loliccompiler for Jflex by RobbinNi
*/

package lexer;

import java_cup.runtime.*;

import parser.Symbols;

import table.SyntacticTable;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>D:/4415 ±‡“Î‘≠¿Ì MS109/loliccompiler/src/lexer/loliccompiler.flex</tt>
 */
public class Yylex implements java_cup.runtime.Scanner, Symbols {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int YYSTRING = 2;
  public static final int YYCOMMENT = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\15\1\72\1\16"+
    "\1\14\1\6\1\70\1\63\1\47\1\50\1\51\1\23\1\66\1\53"+
    "\1\67\1\73\1\4\1\10\3\22\4\11\2\7\1\14\1\52\1\64"+
    "\1\54\1\65\2\14\6\13\24\5\1\57\1\17\1\60\1\62\1\6"+
    "\1\14\1\32\1\21\1\30\1\27\1\40\1\37\1\5\1\31\1\26"+
    "\1\5\1\43\1\41\1\5\1\34\1\25\1\46\1\5\1\33\1\35"+
    "\1\20\1\36\1\24\1\42\1\12\1\45\1\44\1\55\1\61\1\56"+
    "\1\71\201\14\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uff10\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\2\2\1\3\1\4\2\5\1\6\2\4"+
    "\1\7\11\4\1\1\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\1\2\36\1\37\1\40\1\41\1\42\1\0"+
    "\2\4\1\43\1\44\2\4\1\45\11\4\2\0\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\1\54\1\55\1\56"+
    "\1\57\1\60\1\61\1\62\1\63\1\64\1\65\1\66"+
    "\1\67\1\0\1\67\1\0\1\70\2\37\1\71\3\4"+
    "\1\72\6\4\1\73\2\4\1\74\4\0\1\75\1\76"+
    "\2\0\2\4\1\77\1\4\1\100\4\4\1\101\1\4"+
    "\1\0\1\102\1\0\1\103\1\4\1\104\4\4\1\105"+
    "\1\106\1\0\2\4\1\107\1\110\1\111\1\112\1\113"+
    "\1\4\1\114";

  private static int [] zzUnpackAction() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\74\0\170\0\264\0\360\0\264\0\u012c\0\u0168"+
    "\0\u01a4\0\u01e0\0\264\0\u021c\0\u0258\0\u0294\0\u02d0\0\u030c"+
    "\0\u0348\0\u0384\0\u03c0\0\u03fc\0\u0438\0\u0474\0\u04b0\0\u04ec"+
    "\0\264\0\264\0\264\0\264\0\u0528\0\264\0\264\0\264"+
    "\0\264\0\u0564\0\u05a0\0\u05dc\0\u0618\0\u0654\0\u0690\0\u06cc"+
    "\0\u0708\0\264\0\u0744\0\264\0\u0780\0\264\0\u07bc\0\264"+
    "\0\u07f8\0\u0834\0\264\0\264\0\u0870\0\u08ac\0\u08e8\0\u0924"+
    "\0\264\0\264\0\u0960\0\u099c\0\u0168\0\u09d8\0\u0a14\0\u0a50"+
    "\0\u0a8c\0\u0ac8\0\u0b04\0\u0b40\0\u0b7c\0\u0bb8\0\u0bf4\0\u0c30"+
    "\0\264\0\264\0\264\0\264\0\264\0\264\0\264\0\u0c6c"+
    "\0\264\0\u0ca8\0\264\0\264\0\264\0\264\0\264\0\264"+
    "\0\264\0\u0ce4\0\u0d20\0\264\0\u0ce4\0\264\0\u0d5c\0\264"+
    "\0\u08ac\0\u0d98\0\u0dd4\0\u0e10\0\u0168\0\u0e4c\0\u0e88\0\u0ec4"+
    "\0\u0f00\0\u0f3c\0\u0f78\0\u0168\0\u0fb4\0\u0ff0\0\264\0\u102c"+
    "\0\u1068\0\u10a4\0\u10e0\0\264\0\264\0\u111c\0\u1158\0\u1194"+
    "\0\u11d0\0\u0168\0\u120c\0\u0168\0\u1248\0\u1284\0\u12c0\0\u12fc"+
    "\0\u0168\0\u1338\0\u1374\0\264\0\u13b0\0\264\0\u13ec\0\u0168"+
    "\0\u1428\0\u1464\0\u14a0\0\u14dc\0\u0168\0\u0168\0\u1518\0\u1554"+
    "\0\u1590\0\u0168\0\u0168\0\u0168\0\264\0\u0168\0\u15cc\0\u0168";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\2\6\1\7\1\10\1\4\1\11\1\12"+
    "\1\11\2\10\1\4\1\6\1\13\1\4\1\14\1\15"+
    "\1\11\1\16\1\17\1\10\1\20\1\10\1\21\2\10"+
    "\1\22\1\10\1\23\1\24\1\25\1\26\1\10\1\27"+
    "\4\10\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\1\54\1\55\2\4"+
    "\13\55\1\56\1\57\54\55\23\60\1\61\50\60\76\0"+
    "\1\6\75\0\1\62\16\0\1\63\30\0\1\64\24\0"+
    "\7\10\4\0\3\10\1\0\23\10\34\0\3\11\10\0"+
    "\1\11\61\0\2\65\1\66\7\0\1\65\56\0\7\10"+
    "\4\0\3\10\1\0\21\10\1\67\1\10\32\0\7\10"+
    "\4\0\3\10\1\0\7\10\1\70\13\10\31\0\1\71"+
    "\47\0\1\72\24\0\7\10\4\0\3\10\1\0\1\10"+
    "\1\73\21\10\32\0\7\10\4\0\3\10\1\0\10\10"+
    "\1\74\2\10\1\75\7\10\32\0\7\10\4\0\3\10"+
    "\1\0\1\10\1\76\3\10\1\77\15\10\32\0\7\10"+
    "\4\0\3\10\1\0\14\10\1\100\6\10\32\0\7\10"+
    "\4\0\1\101\2\10\1\0\2\10\1\102\20\10\32\0"+
    "\7\10\4\0\3\10\1\0\10\10\1\103\12\10\32\0"+
    "\7\10\4\0\3\10\1\0\1\10\1\104\21\10\32\0"+
    "\7\10\4\0\3\10\1\0\15\10\1\105\5\10\32\0"+
    "\7\10\4\0\3\10\1\0\5\10\1\106\15\10\31\0"+
    "\12\107\1\0\1\110\27\107\1\0\24\107\54\0\1\111"+
    "\73\0\1\112\4\0\1\113\66\0\1\114\73\0\1\115"+
    "\6\0\1\116\64\0\1\117\7\0\1\120\63\0\1\121"+
    "\10\0\1\122\62\0\1\123\11\0\1\124\61\0\1\125"+
    "\10\0\1\126\1\0\1\127\60\0\1\130\73\0\1\131"+
    "\17\0\1\55\2\0\13\55\2\0\54\55\10\0\1\132"+
    "\1\0\1\133\3\0\4\134\1\135\10\0\2\134\2\0"+
    "\1\134\7\0\1\134\30\0\1\136\67\0\1\62\1\137"+
    "\1\140\71\62\10\0\2\65\10\0\1\65\60\0\3\141"+
    "\1\0\1\141\5\0\2\141\4\0\2\141\1\0\1\141"+
    "\4\0\2\141\40\0\7\10\4\0\3\10\1\0\22\10"+
    "\1\142\32\0\7\10\4\0\3\10\1\0\14\10\1\143"+
    "\6\10\32\0\7\10\4\0\3\10\1\0\2\10\1\144"+
    "\20\10\32\0\7\10\4\0\1\145\2\10\1\0\23\10"+
    "\32\0\7\10\4\0\3\10\1\0\10\10\1\146\12\10"+
    "\32\0\7\10\4\0\3\10\1\0\6\10\1\147\14\10"+
    "\32\0\7\10\4\0\1\150\2\10\1\0\23\10\32\0"+
    "\7\10\4\0\3\10\1\0\7\10\1\151\13\10\32\0"+
    "\7\10\4\0\3\10\1\0\20\10\1\152\2\10\32\0"+
    "\7\10\4\0\3\10\1\0\2\10\1\153\20\10\32\0"+
    "\7\10\4\0\3\10\1\0\7\10\1\154\13\10\32\0"+
    "\7\10\4\0\3\10\1\0\11\10\1\155\11\10\32\0"+
    "\7\10\4\0\3\10\1\0\2\10\1\156\20\10\74\0"+
    "\1\157\34\0\1\160\1\0\1\161\3\0\4\162\1\163"+
    "\10\0\2\162\2\0\1\162\7\0\1\162\100\0\1\164"+
    "\73\0\1\165\27\0\2\166\10\0\1\166\60\0\3\167"+
    "\1\0\1\167\5\0\2\167\4\0\2\167\1\0\1\167"+
    "\4\0\2\167\35\0\1\140\76\0\7\10\4\0\3\10"+
    "\1\0\14\10\1\170\6\10\32\0\7\10\4\0\3\10"+
    "\1\0\6\10\1\171\14\10\32\0\7\10\4\0\3\10"+
    "\1\0\3\10\1\172\17\10\32\0\7\10\4\0\1\173"+
    "\2\10\1\0\23\10\32\0\7\10\4\0\3\10\1\0"+
    "\7\10\1\174\13\10\32\0\7\10\4\0\3\10\1\0"+
    "\12\10\1\175\10\10\32\0\7\10\4\0\3\10\1\0"+
    "\12\10\1\176\10\10\32\0\7\10\4\0\3\10\1\0"+
    "\14\10\1\177\6\10\32\0\7\10\4\0\3\10\1\0"+
    "\1\10\1\200\21\10\32\0\7\10\4\0\3\10\1\0"+
    "\14\10\1\201\6\10\32\0\7\10\4\0\3\10\1\0"+
    "\15\10\1\202\5\10\35\0\2\203\10\0\1\203\24\0"+
    "\1\204\33\0\3\205\1\0\1\205\5\0\2\205\4\0"+
    "\2\205\1\0\1\205\4\0\2\205\102\0\1\204\34\0"+
    "\2\203\10\0\1\203\61\0\2\206\10\0\1\206\60\0"+
    "\3\206\1\0\1\206\5\0\2\206\4\0\2\206\1\0"+
    "\1\206\4\0\2\206\40\0\7\10\4\0\3\10\1\0"+
    "\3\10\1\207\17\10\32\0\7\10\4\0\3\10\1\0"+
    "\17\10\1\210\3\10\32\0\7\10\4\0\3\10\1\0"+
    "\2\10\1\211\20\10\32\0\7\10\4\0\3\10\1\0"+
    "\7\10\1\212\13\10\32\0\7\10\4\0\3\10\1\0"+
    "\4\10\1\213\16\10\32\0\7\10\4\0\3\10\1\0"+
    "\1\10\1\214\21\10\32\0\7\10\4\0\3\10\1\0"+
    "\10\10\1\215\12\10\32\0\7\10\4\0\3\10\1\0"+
    "\14\10\1\216\6\10\35\0\2\217\10\0\1\217\60\0"+
    "\3\217\1\0\1\217\5\0\2\217\4\0\2\217\1\0"+
    "\1\217\4\0\2\217\40\0\7\10\4\0\3\10\1\0"+
    "\14\10\1\220\6\10\32\0\7\10\4\0\3\10\1\0"+
    "\10\10\1\221\12\10\32\0\7\10\4\0\3\10\1\0"+
    "\10\10\1\222\12\10\32\0\7\10\4\0\1\223\2\10"+
    "\1\0\23\10\32\0\7\10\4\0\3\10\1\0\13\10"+
    "\1\224\7\10\74\0\1\225\31\0\7\10\4\0\3\10"+
    "\1\0\13\10\1\226\7\10\32\0\7\10\4\0\3\10"+
    "\1\0\12\10\1\227\10\10\32\0\7\10\4\0\3\10"+
    "\1\0\14\10\1\230\6\10\25\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5640];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\1\1\1\11\4\1\1\11\15\1\4\11"+
    "\1\1\4\11\10\1\1\11\1\1\1\11\1\1\1\11"+
    "\1\1\1\11\2\1\2\11\1\1\1\0\2\1\2\11"+
    "\14\1\2\0\7\11\1\1\1\11\1\1\7\11\1\1"+
    "\1\0\1\11\1\0\1\11\1\1\1\11\16\1\1\11"+
    "\4\0\2\11\2\0\13\1\1\0\1\11\1\0\1\11"+
    "\10\1\1\0\5\1\1\11\3\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    StringBuffer buffer = new StringBuffer();
    SyntacticTable table;

    public void setTable(SyntacticTable table)  {
        this.table = table;
    }

    private Symbol symbol(int type) {
        //System.out.println("Token found : " + type);
        return new Symbol(type, yyline, yycolumn);
    }

    private Symbol symbol(int type, Object value) {
        //System.out.println("Token found : " + type + "  <" + value + ">  ");
        return new Symbol(type, yyline, yycolumn, value);
    }

    private void reportError(String message) throws Error {
        throw new Error("Scanning error in line " + yyline + ", column " + yycolumn + " : " + message + "\n") ;
    }

    private int chNum(char ch) {
        if (ch >= '0' && ch <= '9') {
            return ch - '0';
        } else if (ch >= 'A' && ch <= 'F') {
            return ch - 'A' + 10;
        } else {
            return ch - 'a' + 10;
        }
    }

    private char lexANC(String s) {
        char ch;
        if (s.charAt(1) == 'x') {
            ch = (char)((chNum(s.charAt(2)) << 4) | chNum(s.charAt(3)));
        } else {
            ch = (char)((chNum(s.charAt(1)) << 6) | (chNum(s.charAt(2)) << 3) | chNum(s.charAt(3)));
        }
        return ch;
    }

    private char lexTDC(String s) {
        switch (s.charAt(1)) {
            case 'b'  : return '\b';
            case 'f'  : return '\f';
            case 'n'  : return '\n';
            case 'r'  : return '\r';
            case 't'  : return '\t';
            case '\\' : return '\\';
            case '\'' : return '\'';
            case '\"' : return '\"';
            case '0'  : return '\0';
        }
        return '\0';
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 178) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          {     {
        if (yystate() == YYCOMMENT) {
            reportError("Comment reaches the end of file.");
        }
        return symbol(EOF, null);
    }
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { reportError("Illegal character <" + yytext() + ">");
            }
          case 77: break;
          case 2: 
            { /* ignored */
            }
          case 78: break;
          case 3: 
            { return symbol(DIV);
            }
          case 79: break;
          case 4: 
            { return symbol(table.typeOf(yytext()), yytext());
            }
          case 80: break;
          case 5: 
            { return symbol(INTEGER, Integer.parseInt(yytext()));
            }
          case 81: break;
          case 6: 
            { buffer.setLength(0); yybegin(YYSTRING);
            }
          case 82: break;
          case 7: 
            { return symbol(MUL);
            }
          case 83: break;
          case 8: 
            { return symbol(PARAL);
            }
          case 84: break;
          case 9: 
            { return symbol(PARAR);
            }
          case 85: break;
          case 10: 
            { return symbol(COLON);
            }
          case 86: break;
          case 11: 
            { return symbol(COMMA);
            }
          case 87: break;
          case 12: 
            { return symbol(ASSIGN);
            }
          case 88: break;
          case 13: 
            { return symbol(CURLYL);
            }
          case 89: break;
          case 14: 
            { return symbol(CURLYR);
            }
          case 90: break;
          case 15: 
            { return symbol(SQUARL);
            }
          case 91: break;
          case 16: 
            { return symbol(SQUARR);
            }
          case 92: break;
          case 17: 
            { return symbol(OR);
            }
          case 93: break;
          case 18: 
            { return symbol(XOR);
            }
          case 94: break;
          case 19: 
            { return symbol(ADRESS);
            }
          case 95: break;
          case 20: 
            { return symbol(LESS);
            }
          case 96: break;
          case 21: 
            { return symbol(GREATER);
            }
          case 97: break;
          case 22: 
            { return symbol(ADD);
            }
          case 98: break;
          case 23: 
            { return symbol(SUB);
            }
          case 99: break;
          case 24: 
            { return symbol(MOD);
            }
          case 100: break;
          case 25: 
            { return symbol(TILDE);
            }
          case 101: break;
          case 26: 
            { return symbol(NOT);
            }
          case 102: break;
          case 27: 
            { return symbol(DOT);
            }
          case 103: break;
          case 28: 
            { buffer.append(yytext());
            }
          case 104: break;
          case 29: 
            { yybegin(YYINITIAL);
                      return symbol(STRING, buffer.toString());
            }
          case 105: break;
          case 30: 
            { 
            }
          case 106: break;
          case 31: 
            { /* ignore */
            }
          case 107: break;
          case 32: 
            { yybegin(YYCOMMENT);
            }
          case 108: break;
          case 33: 
            { return symbol(DIV_ASSIGN);
            }
          case 109: break;
          case 34: 
            { return symbol(INTEGER, Integer.parseInt(yytext().substring(1), 8));
            }
          case 110: break;
          case 35: 
            { reportError("Unexpected end of a comment.");
            }
          case 111: break;
          case 36: 
            { return symbol(MUL_ASSIGN);
            }
          case 112: break;
          case 37: 
            { return symbol(IF);
            }
          case 113: break;
          case 38: 
            { return symbol(EQ_OP);
            }
          case 114: break;
          case 39: 
            { return symbol(OR_ASSIGN);
            }
          case 115: break;
          case 40: 
            { return symbol(OR_OP);
            }
          case 116: break;
          case 41: 
            { return symbol(XOR_ASSIGN);
            }
          case 117: break;
          case 42: 
            { return symbol(AND_ASSIGN);
            }
          case 118: break;
          case 43: 
            { return symbol(AND_OP);
            }
          case 119: break;
          case 44: 
            { return symbol(LE_OP);
            }
          case 120: break;
          case 45: 
            { return symbol(SHL_OP);
            }
          case 121: break;
          case 46: 
            { return symbol(GE_OP);
            }
          case 122: break;
          case 47: 
            { return symbol(SHR_OP);
            }
          case 123: break;
          case 48: 
            { return symbol(ADD_ASSIGN);
            }
          case 124: break;
          case 49: 
            { return symbol(INC_OP);
            }
          case 125: break;
          case 50: 
            { return symbol(SUB_ASSIGN);
            }
          case 126: break;
          case 51: 
            { return symbol(PTR_OP);
            }
          case 127: break;
          case 52: 
            { return symbol(DEC_OP);
            }
          case 128: break;
          case 53: 
            { return symbol(MOD_ASSIGN);
            }
          case 129: break;
          case 54: 
            { return symbol(NE_OP);
            }
          case 130: break;
          case 55: 
            { buffer.append(lexTDC(yytext()));
            }
          case 131: break;
          case 56: 
            { yybegin(YYINITIAL);
            }
          case 132: break;
          case 57: 
            { return symbol(INTEGER, Integer.parseInt(yytext().substring(2), 16));
            }
          case 133: break;
          case 58: 
            { return symbol(INT);
            }
          case 134: break;
          case 59: 
            { return symbol(FOR);
            }
          case 135: break;
          case 60: 
            { return symbol(CHARACTER, yytext().charAt(1));
            }
          case 136: break;
          case 61: 
            { return symbol(SHL_ASSIGN);
            }
          case 137: break;
          case 62: 
            { return symbol(SHR_ASSIGN);
            }
          case 138: break;
          case 63: 
            { return symbol(VOID);
            }
          case 139: break;
          case 64: 
            { return symbol(CHAR);
            }
          case 140: break;
          case 65: 
            { return symbol(ELSE);
            }
          case 141: break;
          case 66: 
            { return symbol(CHARACTER, lexTDC(yytext().substring(1)));
            }
          case 142: break;
          case 67: 
            { buffer.append(lexANC(yytext()));
            }
          case 143: break;
          case 68: 
            { return symbol(BREAK);
            }
          case 144: break;
          case 69: 
            { return symbol(UNION);
            }
          case 145: break;
          case 70: 
            { return symbol(WHILE);
            }
          case 146: break;
          case 71: 
            { return symbol(RETURN);
            }
          case 147: break;
          case 72: 
            { return symbol(STRUCT);
            }
          case 148: break;
          case 73: 
            { return symbol(SIZEOF);
            }
          case 149: break;
          case 74: 
            { return symbol(CHARACTER, lexANC(yytext().substring(1)));
            }
          case 150: break;
          case 75: 
            { return symbol(TYPEDEF);
            }
          case 151: break;
          case 76: 
            { return symbol(CONTINUE);
            }
          case 152: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
